# Generated by Django 5.2.10 on 2026-01-09 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="life_stage",
            field=models.CharField(
                choices=[
                    ("adult", "Adult"),
                    ("pregnant", "Pregnant"),
                    ("lactating", "Lactating"),
                ],
                max_length=20,
            ),
        ),
    ]
